/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOn: typeof import('./src/components/layout/AddOn.vue')['default']
    CommonButton: typeof import('./src/components/common/CommonButton.vue')['default']
    CommonOnOff: typeof import('./src/components/common/CommonOnOff.vue')['default']
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    FirstNoticeMain: typeof import('./src/components/page/Board/Notice/FirstNoticeMain.vue')['default']
    FirstNoticeModal: typeof import('./src/components/page/Board/Notice/FirstNoticeModal.vue')['default']
    FirstNoticeSearch: typeof import('./src/components/page/Board/Notice/FirstNoticeSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HirePostMain: typeof import('./src/components/page/Hire/HirePostMain.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    LunchMenu: typeof import('./src/components/layout/AddOnPack/LunchMenu.vue')['default']
    MusicBox: typeof import('./src/components/layout/AddOnPack/MusicBox.vue')['default']
    NoticeDetail: typeof import('./src/components/page/Board/Notice/NoticeDetail.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PostMain: typeof import('./src/components/page/Jobs/Post/PostMain.vue')['default']
    PostSearch: typeof import('./src/components/page/Jobs/Post/PostSearch.vue')['default']
    PrevResumeDetail: typeof import('./src/components/page/Apply/Resume/prev/prevResumeDetail.vue')['default']
    PrevResumeMain: typeof import('./src/components/page/Apply/Resume/prev/prevResumeMain.vue')['default']
    PrevResumeWrite: typeof import('./src/components/page/Apply/Resume/prev/prevResumeWrite.vue')['default']
    ResumeDetail: typeof import('./src/components/page/Apply/Resume/ResumeDetail.vue')['default']
    ResumeMail: typeof import('./src/components/page/Apply/Resume/prev/ResumeMail.vue')['default']
    ResumeMain: typeof import('./src/components/page/Apply/Resume/ResumeMain.vue')['default']
    ResumeNew: typeof import('./src/components/page/Apply/Resume/ResumeNew.vue')['default']
    ResumeNewButton: typeof import('./src/components/page/Apply/Resume/ResumeNewButton.vue')['default']
    ResumeWrite: typeof import('./src/components/page/Apply/Resume/prev/ResumeWrite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkinImage: typeof import('./src/components/layout/AddOnPack/SkinImage.vue')['default']
    SnowAni: typeof import('./src/components/layout/AddOnPack/SnowAni.vue')['default']
  }
}
