/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOn: typeof import('./src/components/layout/AddOn.vue')['default']
    AdminPostMain: typeof import('./src/components/page/Approval/AdminPostMain.vue')['default']
    AdminPostSearch: typeof import('./src/components/page/Approval/AdminPostSearch.vue')['default']
    ApprovalPostMain: typeof import('./src/components/page/Approval/ApprovalPostMain.vue')['default']
    ApprovalPostSearch: typeof import('./src/components/page/Approval/ApprovalPostSearch.vue')['default']
    AsIsQnaDetailModal: typeof import('./src/components/page/Qna/AsIsQnaDetailModal.vue')['default']
    AsIsQnaMain: typeof import('./src/components/page/Qna/AsIsQnaMain.vue')['default']
    AsIsQnaSerchWrite: typeof import('./src/components/page/Qna/AsIsQnaSerchWrite.vue')['default']
    CommonButton: typeof import('./src/components/common/CommonButton.vue')['default']
    CommonOnOff: typeof import('./src/components/common/CommonOnOff.vue')['default']
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    FirstNoticeMain: typeof import('./src/components/page/Board/Notice/FirstNoticeMain.vue')['default']
    FirstNoticeModal: typeof import('./src/components/page/Board/Notice/FirstNoticeModal.vue')['default']
    FirstNoticeSearch: typeof import('./src/components/page/Board/Notice/FirstNoticeSearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HirePostEditor: typeof import('./src/components/page/Hire/HirePostEditor.vue')['default']
    HirePostMain: typeof import('./src/components/page/Hire/HirePostMain.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    LunchMenu: typeof import('./src/components/layout/AddOnPack/LunchMenu.vue')['default']
    MusicBox: typeof import('./src/components/layout/AddOnPack/MusicBox.vue')['default']
    NoticeDetail: typeof import('./src/components/page/Board/Notice/NoticeDetail.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PostMain: typeof import('./src/components/page/Jobs/Post/PostMain.vue')['default']
    PostSearch: typeof import('./src/components/page/Jobs/Post/PostSearch.vue')['default']
    QnaDetailModal: typeof import('./src/components/page/Qna/QnaDetailModal.vue')['default']
    QnaMain: typeof import('./src/components/page/Qna/QnaMain.vue')['default']
    QnaSerchWrite: typeof import('./src/components/page/Qna/QnaSerchWrite.vue')['default']
    ResumeDetail: typeof import('./src/components/page/Resume/ResumeDetail/ResumeDetail.vue')['default']
    ResumeMain: typeof import('./src/components/page/Resume/ResumeMain/ResumeMain.vue')['default']
    ResumeWrite: typeof import('./src/components/page/Resume/ResumeEdit/ResumeWrite.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkinImage: typeof import('./src/components/layout/AddOnPack/SkinImage.vue')['default']
    SnowAni: typeof import('./src/components/layout/AddOnPack/SnowAni.vue')['default']
  }
}
